version: '3'

tasks:
    setup:
        desc: Setup the project dependencies
        cmds:
            - git submodule update --init --recursive || true
            - git submodule update --recursive --remote
            - go mod download
            - pre-commit install && pre-commit install --hook-type commit-msg && pre-commit install-hooks
    update:
        desc: Update the project dependencies
        cmds:
            - go mod tidy && go get -u ./... &> /dev/null
            - pre-commit autoupdate
    lint:
        desc: Lint the project
        cmds:
            - pre-commit run --show-diff-on-failure --color=always --all-files
    # protobuf
    buf:generate:
        desc: Generate gRPC types and code from proto files
        cmds:
            - rm -rf gen
            - npx buf generate
    buf:lint:
        desc: Lint the protobuf files
        cmds:
            - npx buf lint
    buf:format:
        desc: Format the protobuf files
        cmds:
            - npx buf format